#!/bin/ash
#welcome

export TEXTDOMAIN=welcome1stboot
export OUTPUT_CHARSET=UTF-8

. /etc/DISTRO_SPECS
W_MSG="$(gettext "Welcome,
You have successfully booted Kelpup!!!...")"

LABEL_INTERNET="$(gettext "When you chose your bootable USB in the boot menu, your computer loaded the Kelpup operating system from your USB into RAM. Now Kelpup is running on your computer as the main operating system!")"
LABEL_NEEDHELP="$(gettext "<b>What now?</b>
Just click the next button, and we will teach you how to use the terminal to interact with your computer!')"
LABEL_SETUP="$(gettext '<b>Kelpup = Kelpie Puppy</b>
Kelpies are shape-shifting water spirits in Scottish folklore :)')"


LABEL_INTERNET="$(gettext "<b>Booting Kelpup</b>
${LABEL_INTERNET}")"

export WELCOME_DIALOG='
<window title="'$(gettext 'Welcome')'" icon-name="gtk-info" resizable="false">
<vbox>
	<hbox border-width="7" space-expand="true" space-fill="true">
      <pixmap icon_size="4"><input file>/usr/share/doc/puppylogo96.png</input></pixmap>
      <text use-markup="true"><label>"<big>'"${W_MSG}"'</big>"</label></text>
    </hbox>
    <hbox border-width="7" space-expand="true" space-fill="true">
      <text space-expand="false" space-fill="false"><label>""</label></text>
      <text xalign="0" use-markup="true" space-expand="true" space-fill="true"><label>"'"${LABEL_INTERNET}"'"</label></text>
      <vbox space-expand="false" space-fill="false">
        <button>
          '$(/usr/lib/gtkdialog/xml_button-icon /usr/local/lib/X11/pixmaps/connect48.png huge)'
          <action>/usr/sbin/connectwizard & </action>
        </button>
      </vbox>
    </hbox>
    <hseparator></hseparator>
    <hbox border-width="7" space-expand="true" space-fill="true">
      <text space-expand="false" space-fill="false"><label>""</label></text>
      <text xalign="0" use-markup="true" space-expand="true" space-fill="true"><label>"'"${LABEL_SETUP}"'"</label></text>
      <vbox space-expand="false" space-fill="false">
        <button>
         '$(/usr/lib/gtkdialog/xml_button-icon /usr/local/lib/X11/pixmaps/configuration48.png huge)'
         <action>/usr/sbin/wizardwizard & </action>
        </button>
      </vbox>
    </hbox>
    <hseparator></hseparator>

    <hbox border-width="7" space-expand="true" space-fill="true">
      <text space-expand="false" space-fill="false"><label>""</label></text>
      <text xalign="0" use-markup="true" space-expand="true" space-fill="true"><label>"'"${LABEL_NEEDHELP}"'"</label></text>
      <vbox space-expand="false" space-fill="false">
        <text space-expand="false" space-fill="false"><label>""</label></text>
        <button>
         '$(/usr/lib/gtkdialog/xml_button-icon help.svg huge)'
         <action>basichtmlviewer file:///usr/share/doc/index.html & </action>
        </button>
      </vbox>
    </hbox>
    <hbox border-width="7" space-expand="true" space-fill="true">
      <pixmap><input file>/usr/share/doc/tray.png</input></pixmap>
      <text xalign="0" use-markup="true" space-expand="true" space-fill="true"><label>"'$(gettext "...mouse-over and click the tray applets!")'"</label></text>
    </hbox>
  </vbox>
</window>'

gtkdialog --center -p WELCOME_DIALOG 2>/dev/null

### END ###
